on:
  push:
    branches:
      - master
      - gh-actions

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  style_lint:
    name: Lint style
    runs-on: ubuntu-latest
    steps:
      - name: Check for long lines
        if: always()
        run: |
          ! (find BonnAnalysis -name "*.lean" -type f -exec grep -E -H -n '^.{101,}$' {} \; | grep -v -E 'https?://')

  build_project:
    runs-on: ubuntu-latest
    name: Build project
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install elan
        run: |
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain leanprover/lean4:4.0.0 # Install Lean 4

      - name: Update docgen4
        run: ~/.elan/bin/lake -R -Kenv=dev update «doc-gen4»

      - name: Get cache
        run: ~/.elan/bin/lake -Kenv=dev exe cache get || true

      - name: Build project
        run: ~/.elan/bin/lake -Kenv=dev build BonnAnalysis

      - name: Cache mathlib docs
        uses: actions/cache@v3
        with:
          path: |
            .lake/build/doc/Init
            .lake/build/doc/Lake
            .lake/build/doc/Lean
            .lake/build/doc/Std
            .lake/build/doc/Mathlib
            .lake/build/doc/declarations
            !.lake/build/doc/declarations/declaration-data-BonnAnalysis*
          key: MathlibDoc-${{ hashFiles('lake-manifest.json') }}
          restore-keys: |
            MathlibDoc- # Cache Mathlib documentation to save rebuild time

      # - name: Cache documentation build artifacts
      #   uses: actions/cache@v3
      #   with:
      #     path: .lake/build
      #     key: build-artifacts-${{ runner.os }}-${{ hashFiles('lake-manifest.json') }}
      #     restore-keys: |
      #       build-artifacts-

      - name: Build documentation
        run: ~/.elan/bin/lake -Kenv=dev build BonnAnalysis:docs # Build project documentation

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Cache apt packages
        uses: actions/cache@v3
        with:
          path: |
            /var/cache/apt/archives
            !/var/cache/apt/archives/partial
          key: apt-cache-${{ runner.os }}-${{ hashFiles('blueprint/requirements.txt') }}
          restore-keys: |
            apt-cache-${{ runner.os }}-

      - name: Cache apt package lists
        uses: actions/cache@v3
        with:
          path: |
            /var/lib/apt/lists
            !/var/lib/apt/lists/partial
            !/var/lib/apt/lists/lock
          key: apt-lists-${{ runner.os }}-${{ hashFiles('blueprint/requirements.txt') }}
          restore-keys: |
            apt-lists-${{ runner.os }}-

      - name: Install blueprint apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz libgraphviz-dev pdf2svg dvisvgm texlive-full # Install necessary system packages for blueprint

      - name: Cache blueprint dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: blueprint-dependencies-${{ runner.os }}-${{ hashFiles('blueprint/requirements.txt') }}
          restore-keys: |
            blueprint-dependencies- # Cache Python dependencies for blueprint

      - name: Install blueprint dependencies
        run: |
          cd blueprint && pip install -r requirements.txt # Install Python dependencies for blueprint

      - name: Build blueprint and copy to `docs/blueprint`
        run: inv all

      - name: Remove lake files from documentation
        run: |
          find .lake/build/doc -name "*.trace" -delete
          find .lake/build/doc -name "*.hash" -delete

      - name: Copy documentation to `docs/docs`
        run: |
          sudo chown -R runner docs
          cp -r .lake/build/doc docs/docs # Copy the built documentation to the correct directory

      - name: Bundle dependencies
        uses: ruby/setup-ruby@v1
        with:
          working-directory: docs
          ruby-version: "3.0"
          bundler-cache: true

      - name: Bundle website
        working-directory: docs
        run: JEKYLL_ENV=production bundle exec jekyll build # Build the Jekyll site for production

      - name: Upload docs & blueprint artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1